# Generated by Django 3.1.5 on 2021-01-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogbreeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
    ]
