# Generated by Django 3.1.5 on 2021-01-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogbreeds', '0003_remove_dog_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_id', models.IntegerField()),
                ('dog_name', models.CharField(max_length=64)),
                ('html_content', models.TextField()),
            ],
        ),
    ]
