# Generated by Django 3.1.5 on 2021-01-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogbreeds', '0004_dogdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dogdetails',
            options={'verbose_name_plural': 'Dog Details'},
        ),
        migrations.AddField(
            model_name='dogdetails',
            name='dog',
            field=models.ManyToManyField(to='dogbreeds.Dog'),
        ),
    ]
